[versions]
# Core Minecraft dependencies
brigadier = "1.3.10"
paper = "1.21.11-R0.1-SNAPSHOT"
packetEvents = "2.8.0"

# External "hooks" or plugins that we might interact with
geyser = "2.7.2-SNAPSHOT"
mechanicsCore = "4.2.0-SNAPSHOT"
mythicMobs = "5.9.0"
placeholderApi = "2.11.6"
vault = "1.7.1"
worldedit = "7.3.14"
worldguard = "7.0.14"

# Shaded dependencies
annotations = "26.0.2"
bstats = "3.1.0"
commandApi = "11.1.0"
fastUtil = "8.5.15"
foliaScheduler = "0.7.5"
gson = "2.13.1"
hikariCp = "5.1.0"
jsonSimple = "1.1.1"
kotlin = "1.9.23"
xSeries = "13.6.0"


[libraries]
# Core Minecraft dependencies
brigadier      = { module = "com.mojang:brigadier", version.ref = "brigadier" }
paper          = { module = "io.papermc.paper:paper-api", version.ref = "paper" }
packetEvents   = { module = "com.github.retrooper:packetevents-spigot", version.ref = "packetEvents" }

# External "hooks" or plugins that we might interact with
geyser         = { module = "org.geysermc.geyser:api", version.ref = "geyser" }
mechanicsCore  = { module = "com.cjcrafter:mechanicscore", version.ref = "mechanicsCore" }
mythicMobs     = { module = "io.lumine:Mythic-Dist", version.ref = "mythicMobs" }
placeholderApi = { module = "me.clip:placeholderapi", version.ref = "placeholderApi" }
vault          = { module = "com.github.MilkBowl:VaultAPI", version.ref = "vault" }
worldedit      = { module = "com.sk89q.worldedit:worldedit-bukkit", version.ref = "worldedit" }
worldguard     = { module = "com.sk89q.worldguard:worldguard-bukkit", version.ref = "worldguard" }

# Shaded dependencies
annotations              = { module = "org.jetbrains:annotations", version.ref = "annotations" }
bstats                   = { module = "org.bstats:bstats-bukkit", version.ref = "bstats" }
commandApi               = { module = "dev.jorel:commandapi-paper-core", version.ref = "commandApi" }
commandApiShade          = { module = "dev.jorel:commandapi-paper-shade", version.ref = "commandApi" }
commandApiKotlin         = { module = "dev.jorel:commandapi-kotlin-paper", version.ref = "commandApi" }
fastUtil                 = { module = "it.unimi.dsi:fastutil", version.ref = "fastUtil" }
foliaScheduler           = { module = "com.cjcrafter:foliascheduler", version.ref = "foliaScheduler" }
gson                     = { module = "com.google.code.gson:gson", version.ref = "gson" }
hikariCp                 = { module = "com.zaxxer:HikariCP", version.ref = "hikariCp" }
jsonSimple               = { module = "com.googlecode.json-simple:json-simple", version.ref = "jsonSimple" }
kotlinStdlib             = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin" }
xSeries                  = { module = "com.github.cryptomorin:XSeries", version.ref = "xSeries" }
